{{- $ca := genCA (printf "%s-storage-service-ca" (include "perforator.fullname" .)) 3650 }}
{{- $storageCert := genSignedCert (printf "%s-storage-service" (include "perforator.fullname" .)) nil (list (printf "%s-storage-service" (include "perforator.fullname" .))) 3650 $ca }}
{{- $storageSecretName := printf "%s-storage-crt" (include "perforator.fullname" .) }}
apiVersion: v1
data:
  tls.crt: {{ include "perforator.secrets.lookup" (dict "nameSpace" .Release.Namespace "secretName" $storageSecretName "key" "tls.crt" "defaultVal" $storageCert.Cert) }}
  tls.key: {{ include "perforator.secrets.lookup" (dict "nameSpace" .Release.Namespace "secretName" $storageSecretName "key" "tls.key" "defaultVal" $storageCert.Key) }}
  ca.crt: {{ include "perforator.secrets.lookup" (dict "nameSpace" .Release.Namespace "secretName" $storageSecretName "key" "ca.crt" "defaultVal" $ca.Cert) }}
kind: Secret
metadata:
  name: {{ $storageSecretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
