apiVersion: v1
kind: Service
metadata:
  name: {{ include "perforator.storage.service.name" . }}
  labels:
    {{- include "perforator.selectorLabels" . | nindent 4 }}
    {{- include "perforator.storage.selectorLabels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.proxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "perforator.selectorLabels" . | nindent 4 }}
    {{- include "perforator.storage.selectorLabels" . | nindent 4 }}
  type: {{ .Values.proxy.service.type }}
  {{- with .Values.proxy.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
  - name: grpc
    port: {{ .Values.storage.service.ports.grpc.port }}
    targetPort: grpc
    {{- with .Values.storage.service.ports.grpc.nodePort }}
    nodePort: {{ . }}
    {{- end }}
  {{- range .Values.storage.service.ipFamilies }}
  ipFamilies:
    - {{ . }}
  {{- end}}