{{- if .Values.databases.postgresql.password -}}
apiVersion: v1
data:
  password: {{ .Values.databases.postgresql.password | b64enc | quote }}
kind: Secret
metadata:
  name: {{ include "perforator.fullname" . }}-postgresql-password
  namespace: {{ .Release.Namespace }}
{{- end -}}