{{- if .Values.databases.clickhouse.migrations.enabled }}

{{- if and (or .Values.databases.clickhouse.tls.insecureSkipVerify .Values.databases.clickhouse.insecure) (or .Values.databases.clickhouse.tls.certCAFilename .Values.databases.clickhouse.ca_cert_path) -}}
{{- fail "Cannot specify both TLS certificate verification skip (databases.clickhouse.tls.insecureSkipVerify or databases.clickhouse.insecure) and CA certificate (databases.clickhouse.tls.certCAFilename or databases.clickhouse.ca_cert_path) at the same time" -}}
{{- end -}}

{{- $chhosts := "" }}
{{- $port := "" }}
{{- $endpoints := include "perforator.clickhouse.endpoints" . | fromYamlArray }}
{{- range $endpoints }}
  {{- $hostparts := splitn ":" 2 . }}
  {{- $chhosts = printf "%s%s," $chhosts $hostparts._0 }}
  {{- $port = $hostparts._1 }}
{{- end }}
{{ $chhosts = $chhosts | trimSuffix "," }}

{{- $tlsOpts := "" }}
{{- if .Values.databases.clickhouse.tls.enabled }}
  {{- if or .Values.databases.clickhouse.tls.insecureSkipVerify .Values.databases.clickhouse.insecure }}
    {{- $tlsOpts = printf "%s --tls-trust-all" $tlsOpts }}
  {{- end }}
  
  {{- $caCertPath := include "perforator.clickhouse.tlsCACert" . }}
  {{- if $caCertPath }}
    {{- $tlsOpts = printf "%s --tls-ca %s" $tlsOpts $caCertPath }}
  {{- else if .Values.databases.clickhouse.ca_cert_path }}
    {{- $tlsOpts = printf "%s --tls-ca %s" $tlsOpts .Values.databases.clickhouse.ca_cert_path }}
  {{- end }}
{{- else }}
  {{- $tlsOpts = " --plaintext" }}
{{- end }}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "perforator.fullname" . }}-init-clickhouse-{{ lower (randAlphaNum 5) }}
  labels:
    {{- include "perforator.selectorLabels" . | nindent 4 }}
    {{- include "perforator.migrationsch.selectorLabels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
  {{- with .Values.databases.clickhouse.migrations.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  finalizers: {{ .Values.databases.clickhouse.migrations.finalizers }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: init
        image:  "{{ .Values.databases.clickhouse.migrations.image.repository }}:{{ .Values.databases.clickhouse.migrations.image.tag | default .Chart.AppVersion }}"
        command:
        - /bin/sh
        - -c
        - |
          set -eu
          /perforator/migrate clickhouse up --db {{ .Values.databases.clickhouse.db }} --hosts {{ $chhosts }} --port {{ $port }} --user {{ .Values.databases.clickhouse.user }} --pass ${PASSWORD}{{ if $tlsOpts }} {{ $tlsOpts | trim }}{{ end }} {{ .Values.databases.clickhouse.migrations.extraFlags }}
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              {{ include "perforator.secretKeyRef.clickhouse" . | nindent 14 }}
        {{- range .Values.databases.clickhouse.migrations.extraEnv }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
        volumeMounts:
        {{- if include "perforator.clickhouse.tlsSecretName" . }}
        - name: clickhouse-tls
          mountPath: "/etc/perforator/certificates/clickhouse"
        {{- end }}
        {{- range .Values.databases.clickhouse.migrations.extraMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          subPath: {{ .subPath }}
          readOnly: {{ .readOnly }}
        {{- end }}
      volumes:
      {{- if include "perforator.clickhouse.tlsSecretName" . }}
      - name: clickhouse-tls
        secret:
          secretName: {{ include "perforator.clickhouse.tlsSecretName" . }}
      {{- end }}
      {{- range .Values.databases.clickhouse.migrations.extraMounts }}
      - name: {{ .name }}
        configMap:
          name: {{ .configMap }}
      {{- end }}
  ttlSecondsAfterFinished: {{ .Values.databases.clickhouse.migrations.ttlSecondsAfterFinished }}
{{- end}}